apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-processed-subscription
  namespace: e-commerce-app
spec:
  topic: orderProcessed
  route: /updatePopularProducts
  pubsubname: orderpubsub
scopes:
- recommendation-app
- order-processing-app
