# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
  namespace: e-commerce-app
spec:
  selector:
    app: order-processing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
