apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: stock-update-subscription
  namespace: e-commerce-app
spec:
  topic: stockUpdate
  route: /updateStock
  pubsubname: orderpubsub
scopes:
- stock-management-app
