# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  namespace: e-commerce-app
  labels:
    app: recommendation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-app
  template:
    metadata:
      labels:
        app: recommendation-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "recommendation-app"
        dapr.io/app-port: "5000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: recommendation-app
        image: recommendation-app # Placeholder image name
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000